// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIeRwWm_2bgZgc-BYNcVmqoHr6e55G3_o',
    appId: '1:373960340214:web:7e40f409c4f07cfcea72d7',
    messagingSenderId: '373960340214',
    projectId: 'luba-7f15e',
    authDomain: 'luba-7f15e.firebaseapp.com',
    storageBucket: 'luba-7f15e.appspot.com',
    measurementId: 'G-METKJ1KBWG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6jU3wMEzWO0MqROmlG38LeKtM8dQkvTI',
    appId: '1:373960340214:android:f86476bec2d4c31fea72d7',
    messagingSenderId: '373960340214',
    projectId: 'luba-7f15e',
    storageBucket: 'luba-7f15e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3eJRSkb6ulDGMFef4vb2sHXVUUzHiyQw',
    appId: '1:373960340214:ios:0c0b02fabadde056ea72d7',
    messagingSenderId: '373960340214',
    projectId: 'luba-7f15e',
    storageBucket: 'luba-7f15e.appspot.com',
    iosBundleId: 'com.rickdevelopement.geniztech.resturant.luba',
  );
}
